### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by wlongdong** [RPL-CS-UCL/UCL-AffCorrs#2]
Thank you for sharing such an interesting article. In my experiments, I found that the npy NumPy array in your open-sourced UMD data is 7-dimensional, which is different from the dimensions of the npy file in the affordance's USB. Could you please explain how you chose and processed this?

**Comment by dennisushi** [comment]
The ground truth labels are:

1 - 'grasp'
2 - 'cut'
3 - 'scoop'
4 - 'contain'
5 - 'pound'
6 - 'support'
7 - 'wrap-grasp'

The UMD data has a mask for each affordance. For the USB example, we have only one affordance which does not need to correspond to a particular labelled category (it is unlabelled).
